import { NextResponse, NextRequest } from "next/server";
import { createServerClient } from "@supabase/ssr";

function normalizeEmailHandle(email?: string | null) {
  const emailLocal = email?.split("@")[0] ?? "";
  const normalized = emailLocal
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized || "user";
}

function shouldForceOnboardingForGoogle(
  user: { app_metadata?: { provider?: string }; created_at?: string; email?: string | null },
  profile: { handle?: string | null; created_at?: string | null } | null
) {
  if (user.app_metadata?.provider !== "google") return false;

  // No profile row at all -> definitely a new account path.
  if (!profile) return true;

  // If account was just created and profile handle still equals the auto-generated email handle,
  // treat it as a fresh signup and ask user to complete onboarding form.
  const userCreatedAt = user.created_at ? Date.parse(user.created_at) : Number.NaN;
  const profileCreatedAt = profile.created_at ? Date.parse(profile.created_at) : Number.NaN;
  const now = Date.now();
  const recentWindowMs = 30 * 60 * 1000; // 30 minutes
  const userIsNew = !Number.isNaN(userCreatedAt) && now - userCreatedAt < recentWindowMs;
  const profileIsNew = !Number.isNaN(profileCreatedAt) && now - profileCreatedAt < recentWindowMs;
  const looksAutoGenerated = (profile.handle ?? "") === normalizeEmailHandle(user.email);

  return (userIsNew || profileIsNew) && looksAutoGenerated;
}

export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url);
  const code = searchParams.get("code");

  if (code) {
    const pendingCookies: { name: string; value: string; options: Record<string, unknown> }[] = [];

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return request.cookies.getAll();
          },
          setAll(cookiesToSet) {
            cookiesToSet.forEach((c) => pendingCookies.push(c));
          },
        },
      }
    );

    const { data: { user }, error } = await supabase.auth.exchangeCodeForSession(code);

    if (!error && user) {
      const { data: profile } = await supabase
        .from("profiles")
        .select("handle, created_at")
        .eq("id", user.id)
        .maybeSingle();

      if (shouldForceOnboardingForGoogle(user, profile ?? null)) {
        const response = NextResponse.redirect(`${origin}/onboarding?force=1`);
        pendingCookies.forEach(({ name, value, options }) => {
          response.cookies.set(name, value, options as Parameters<typeof response.cookies.set>[2]);
        });
        return response;
      }

      const redirectTo = profile?.handle
        ? `${origin}/community/user/${profile.handle}`
        : `${origin}/onboarding`;

      const response = NextResponse.redirect(redirectTo);
      pendingCookies.forEach(({ name, value, options }) => {
        response.cookies.set(name, value, options as Parameters<typeof response.cookies.set>[2]);
      });
      return response;
    }
  }

  return NextResponse.redirect(`${origin}/community`);
}
