import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const sections = [
  {
    title: "Acceptance of Terms",
    content: `By accessing or using ScoreSynth ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. These Terms apply to all users of the Service, including visitors, free-tier users, and paid subscribers. ScoreSynth reserves the right to update these Terms at any time, with notice provided via email or a prominent notice on our website.`,
  },
  {
    title: "Description of Service",
    content: `ScoreSynth is an AI-powered platform that transcribes audio files (MP3, WAV), MIDI files, MusicXML, and scanned sheet music into professionally arranged orchestral scores. The Service includes a web-based score editor, a community library for sharing scores, and an API for programmatic access. Feature availability varies by subscription tier.`,
  },
  {
    title: "User Accounts",
    content: `To access most features of ScoreSynth, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate and complete registration information. You may not share your account with others or create accounts for any purpose other than personal or authorized business use. Notify us immediately at support@scoresynth.com if you suspect unauthorized access to your account.`,
  },
  {
    title: "Intellectual Property",
    content: `ScoreSynth and its original content, features, and functionality are and will remain the exclusive property of ScoreSynth, Inc. and its licensors. You retain ownership of any audio files, MIDI, or sheet music you upload to the platform. By uploading content, you grant ScoreSynth a limited, non-exclusive license to process and transform your content solely for the purpose of providing the Service to you. ScoreSynth does not claim ownership of your input files or the resulting scores you generate.`,
  },
  {
    title: "AI-Generated Content & Copyright",
    content: `The scores generated by ScoreSynth's AI are based on your input files and prompts. You are solely responsible for ensuring that you have the right to use and upload any audio, MIDI, or sheet music files you submit to the Service. Uploading copyrighted material without authorization may violate applicable copyright laws. ScoreSynth does not guarantee that AI-generated output is free from third-party intellectual property claims. We provide DMCA takedown procedures for rights holders at legal@scoresynth.com.`,
  },
  {
    title: "Payment & Subscriptions",
    content: `Paid subscriptions are billed monthly or annually in advance. All fees are non-refundable except where required by law or as specified in our Refund Policy. You may cancel your subscription at any time through your account settings; cancellation takes effect at the end of your current billing period. ScoreSynth reserves the right to change pricing with 30 days' notice. Failure to pay may result in suspension or termination of your account.`,
  },
  {
    title: "Prohibited Uses",
    content: `You agree not to use ScoreSynth to: (a) upload or process content that infringes on third-party intellectual property rights without authorization; (b) engage in unauthorized scraping, reverse engineering, or data mining of the platform; (c) attempt to bypass subscription limits or access controls; (d) distribute malicious code or interfere with the platform's infrastructure; (e) use the Service for any unlawful purpose or in violation of these Terms; or (f) impersonate any person or entity.`,
  },
  {
    title: "Disclaimer of Warranties",
    content: `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. SCORESYNTH DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULLEST EXTENT PERMITTED BY LAW, SCORESYNTH DISCLAIMS ALL WARRANTIES, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.`,
  },
  {
    title: "Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SCORESYNTH SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE. IN NO EVENT SHALL SCORESYNTH'S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID TO SCORESYNTH IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.`,
  },
  {
    title: "Governing Law",
    content: `These Terms shall be governed by and construed in accordance with the laws of Belgium and applicable European Union regulations, without regard to conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the competent courts of Belgium.`,
  },
  {
    title: "Changes to Terms",
    content: `We reserve the right to modify these Terms at any time. We will provide at least 14 days' notice of material changes via email or a prominent notice on our platform. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the revised Terms. If you do not agree to the updated Terms, you must stop using the Service before they take effect.`,
  },
  {
    title: "Contact",
    content: `If you have questions about these Terms of Service, please contact us at:\n\nScoreSynth\nEmail: legal@scoresynth.com\nAddress: Meir 67, Oppuurs, Belgium`,
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main style={{ paddingTop: "96px", paddingLeft: "32px", paddingRight: "32px", paddingBottom: "80px" }}>
        <div style={{ maxWidth: "760px", margin: "0 auto" }}>
          {/* Header */}
          <h1 style={{ fontFamily: "Georgia, serif", fontSize: "3rem", lineHeight: 1.1, marginBottom: "12px" }}>
            Terms of Service
          </h1>
          <p style={{ fontSize: "14px", color: "#a89690", marginBottom: "56px" }}>
            Last updated: March 1, 2026
          </p>

          <p style={{ fontSize: "15px", color: "#a89690", lineHeight: 1.8, marginBottom: "48px" }}>
            Please read these Terms of Service carefully before using ScoreSynth. These Terms govern your access to and use of our AI-powered music transcription and orchestration platform, including any content, functionality, and services offered through scoresynth.com.
          </p>

          {/* Sections */}
          {sections.map((section, i) => (
            <div
              key={i}
              style={{
                borderTop: "1px solid rgba(255,255,255,0.08)",
                paddingTop: "32px",
                paddingBottom: "32px",
              }}
            >
              <h2
                style={{
                  fontFamily: "Georgia, serif",
                  fontSize: "1.25rem",
                  fontWeight: 600,
                  marginBottom: "16px",
                  color: "#fff",
                }}
              >
                {i + 1}. {section.title}
              </h2>
              <p style={{ fontSize: "14px", color: "#a89690", lineHeight: 1.8, whiteSpace: "pre-line" }}>
                {section.content}
              </p>
            </div>
          ))}
        </div>
      </main>
      <Footer />
    </>
  );
}
